"""Export functionality for Vigil — CSV, JSON, and report generation."""

import csv
import io
import json
from datetime import UTC, datetime
from typing import Any

from app.events.event_store import EventStore, StoredEvent


def events_to_csv(events: list[StoredEvent]) -> str:
    """Export events as CSV string."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["id", "timestamp", "camera", "type", "confidence", "labels", "snapshot"])
    for event in events:
        writer.writerow([
            event.id,
            event.timestamp,
            event.camera_name,
            event.event_type,
            f"{event.confidence:.3f}",
            ", ".join(event.labels_detected),
            event.snapshot_path,
        ])
    return output.getvalue()


def events_to_json_export(events: list[StoredEvent]) -> str:
    """Export events as formatted JSON."""
    data = {
        "exported_at": datetime.now(UTC).isoformat(),
        "total_events": len(events),
        "events": [
            {
                "id": e.id,
                "timestamp": e.timestamp,
                "camera": e.camera_name,
                "type": e.event_type,
                "confidence": round(e.confidence, 3),
                "labels": e.labels_detected,
                "snapshot": e.snapshot_path,
            }
            for e in events
        ]
    }
    return json.dumps(data, indent=2)


def generate_case_report(case: dict[str, Any], events: list[StoredEvent]) -> str:
    """Generate a text report for a case (markdown format for easy PDF conversion)."""
    lines = [
        f"# Case Report: {case['title']}",
        "",
        f"**Status:** {case['status'].upper()}",
        f"**Created:** {case['created_at']}",
        f"**Description:** {case.get('description', 'No description')}",
        "",
        "---",
        "",
        "## Timeline of Events",
        "",
    ]

    for event in events:
        lines.append(
            f"- **{event.timestamp}** — {event.event_type.replace('_', ' ').title()} "
            f"at {event.camera_name} ({int(event.confidence*100)}% confidence) "
            f"[{', '.join(event.labels_detected)}]"
        )

    if case.get("notes"):
        lines.extend(["", "## Investigation Notes", ""])
        for note in case["notes"]:
            lines.append(f"- **{note['timestamp']}**: {note['text']}")

    lines.extend([
        "",
        "---",
        "",
        f"*Report generated by Vigil AI Video Intelligence Platform*",
        f"*Export timestamp: {datetime.now(UTC).isoformat()}*",
    ])

    return "\n".join(lines)
